### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by nathan30** [wrv/FacebookLoginExample#1]
Hi,

I try your sample and launch it with emulator and with my phone but after connect my account and authorize the application, the app crash 

How I can solve this ?

Thanks

**Comment by wrv** [comment]
Do you have the Facebook App installed? It will crash if not.

**Comment by nathan30** [comment]
Yes I have on my phone the Facebook app. Because I already use the facebook sdk..

**Comment by wrv** [comment]
What does logcat say concerning the crash?

**Comment by nathan30** [comment]
How I can use logcat ?

**Comment by nathan30** [comment]
here is the logcat : 

`04-05 17:39:27.173    1878-1878/awesome.wrvcomputer.science.loginexample D/AndroidRuntime﹕ Shutting down VM
    --------- beginning of crash
04-05 17:39:27.173    1878-1878/awesome.wrvcomputer.science.loginexample E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: awesome.wrvcomputer.science.loginexample, PID: 1878
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=64206, result=-1, data=Intent { (has extras) }} to activity {awesome.wrvcomputer.science.loginexample/awesome.wrvcomputer.science.loginexample.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.facebook.Profile.getFirstName()' on a null object reference
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3539)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3582)
            at android.app.ActivityThread.access$1300(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.facebook.Profile.getFirstName()' on a null object reference
            at awesome.wrvcomputer.science.loginexample.MainActivity.startNewIntent(MainActivity.java:65)
            at awesome.wrvcomputer.science.loginexample.MainActivity.access$000(MainActivity.java:21)
            at awesome.wrvcomputer.science.loginexample.MainActivity$1.onSuccess(MainActivity.java:47)
            at awesome.wrvcomputer.science.loginexample.MainActivity$1.onSuccess(MainActivity.java:42)
            at com.facebook.login.LoginManager.finishLogin(LoginManager.java:508)
            at com.facebook.login.LoginManager.onActivityResult(LoginManager.java:192)
            at com.facebook.login.LoginManager$1.onActivityResult(LoginManager.java:140)
            at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.java:82)
            at awesome.wrvcomputer.science.loginexample.MainActivity.onActivityResult(MainActivity.java:110)
            at android.app.Activity.dispatchActivityResult(Activity.java:6139)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3535)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3582)
            at android.app.ActivityThread.access$1300(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
04-05 17:39:29.479    1878-1878/awesome.wrvcomputer.science.loginexample I/Process﹕ Sending signal. PID: 1878 SIG: 9`

**Comment by wrv** [comment]
Looks like it crashes because Profile is null. Since you use the Facebook SDK I'm guessing you updated the appID in strings and created the app on your Facebook at: https://developers.facebook.com/apps/ ? 

I was getting a random crash at first run when connected to my device, but after reopening the application from the phone it worked fine.

**Comment by nathan30** [comment]
Yes I do that

I re try and keep you update if it's works

**Comment by nathan30** [comment]
I try several times but don't works...
